name 'base_web'
maintainer 'Internal Chef Team'
maintainer_email 'who@chef.io'
issues_url 'https://somewhere.over.the.rainbow'
source_url 'https://way.up,high'
license 'there are rights that I heard of'
description 'once in a lullaby'
version '0.2.2'

depends 'apt'
depends 'yum'
